# Documentation on how to configure the bundle can be found at: 
# https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:

        thumbnail:
            quality: 90
            filters:
                thumbnail:
                    size: [500, 300]
                    # "outbound" crop the image when the size ratio of the input differs
                    mode: outbound

        large:
            quality: 75
            filters:
                scale: 
                    dim: [1200, 600]

        avatar:
            quality: 90
            filters:
                scale: 
                    dim: [100, 100]

        admin_thumbnail:
            quality: 90
            filters:
                thumbnail:
                    size: [200, 200]
