vich_uploader:
    db_driver: orm

    mappings:

        authors:
            uri_prefix: '%uploads_authors_path%'
            upload_destination: '%kernel.project_dir%/public%uploads_authors_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        projects:
            uri_prefix: '%uploads_projects_path%'
            upload_destination: '%kernel.project_dir%/public%uploads_projects_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        posts:
            uri_prefix: '%uploads_posts_path%'
            upload_destination: '%kernel.project_dir%/public%uploads_posts_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        lessons:
            uri_prefix: '%uploads_lessons_path%'
            upload_destination: '%kernel.project_dir%/public%uploads_lessons_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true